name: .NET Build & Test

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0' 
    
    - name: .NET Restore
      run: dotnet restore
    
    - name: .NET Build
      run: dotnet build --configuration Release --no-restore

    - name: .NET Test
      run: dotnet test